camera_index: 0
frame_width: 640
frame_height: 480
min_confidence: 0.5
max_faces: 5
smoothing_alpha: 0.6
class_set: 7
detection_interval: 3
temperature: 1.0
min_face_size: 64
cache_dir: "~/.cache/fer2025"
